# Hands-On Data Preprocessing in Python
Learn how to effectively prepare data for successful data analytics

### Chapter 1: Review of the core modules NumPy, Pandas, and Matplotlib

Hello World! This is a Markdown chunk!

In [8]:
print('Hello World! This is Code Chunk!')

Hello World! This is Code Chunk!


In [9]:
import numpy as np

In [10]:
lst_nums = [2,5,7,11,13,17,23,31,37,41,43,47]
np.mean(lst_nums)

23.083333333333332

In [11]:
lst_nums = [2,5,7,11,13,17,23,31,37,41,43,47]
ary_nums = np.array(lst_nums)
ary_nums.mean()

23.083333333333332

In [12]:
type(lst_nums)

list

In [13]:
type(ary_nums)

numpy.ndarray

In [14]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
np.arange(-7.1,7)

array([-7.1, -6.1, -5.1, -4.1, -3.1, -2.1, -1.1, -0.1,  0.9,  1.9,  2.9,
        3.9,  4.9,  5.9,  6.9])

In [17]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

Example #1

The following is the grade data of ten students. Create a code using NumPy that calcuate and report their grade average. 

    Names = ['Jevon', 'Dawn', 'Kayleigh', 'Jadene', 'Kennedy', 'Kaydee', 'Ansh', 'Flynn', 'Kier', 'Clarence']
    Math_grades = [80, 50, 60, 70, 60, 100, 70, 70, 60, 70]
    Science_grades = [90, 80, 50, 50, 60, 50, 90, 70, 80, 80]
    History_grades = [60, 90, 50, 90, 100, 100, 100, 100, 90, 70]

In [19]:
Names = ['Jevon', 'Dawn', 'Kayleigh', 'Jadene', 'Kennedy', 'Kaydee', 
         'Ansh', 'Flynn', 'Kier', 'Clarence']
Math_grades = [80, 50, 60, 70, 60, 100, 70, 70, 60, 70]
Science_grades = [90, 80, 50, 50, 60, 50, 90, 70, 80, 80]
History_grades = [60, 90, 50, 90, 100, 100, 100, 100, 90, 70]

In [20]:
Average_grades = np.zeros(10)
print(Average_grades)

for i, name in enumerate(Names):  #Imp
    Average_grades[i] = np.mean([Math_grades[i],Science_grades[i],
                                 History_grades[i]])

print(Average_grades)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[76.66666667 73.33333333 53.33333333 70.         73.33333333 83.33333333
 86.66666667 80.         76.66666667 73.33333333]


In [21]:
# better-looking report

for i, name in enumerate(Names):
    print("Average for {} : {}".format(name,Average_grades[i]))

Average for Jevon : 76.66666666666667
Average for Dawn : 73.33333333333333
Average for Kayleigh : 53.333333333333336
Average for Jadene : 70.0
Average for Kennedy : 73.33333333333333
Average for Kaydee : 83.33333333333333
Average for Ansh : 86.66666666666667
Average for Flynn : 80.0
Average for Kier : 76.66666666666667
Average for Clarence : 73.33333333333333


In [22]:
np.linspace(0,1,21) #Imp

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [23]:
np.linspace(10,1000,100)

array([  10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,   90.,
        100.,  110.,  120.,  130.,  140.,  150.,  160.,  170.,  180.,
        190.,  200.,  210.,  220.,  230.,  240.,  250.,  260.,  270.,
        280.,  290.,  300.,  310.,  320.,  330.,  340.,  350.,  360.,
        370.,  380.,  390.,  400.,  410.,  420.,  430.,  440.,  450.,
        460.,  470.,  480.,  490.,  500.,  510.,  520.,  530.,  540.,
        550.,  560.,  570.,  580.,  590.,  600.,  610.,  620.,  630.,
        640.,  650.,  660.,  670.,  680.,  690.,  700.,  710.,  720.,
        730.,  740.,  750.,  760.,  770.,  780.,  790.,  800.,  810.,
        820.,  830.,  840.,  850.,  860.,  870.,  880.,  890.,  900.,
        910.,  920.,  930.,  940.,  950.,  960.,  970.,  980.,  990.,
       1000.])

Example 2

We are interested in finding the value(s) that holds the following mathematical statement.

    x^2-5x+6=0

And imagine that we don’t know that the statement can be simplified easily to find either -1 or +1 will hold the statement.  
    
    x^2-5x+6=(x-2)(x-3)

so we would like to use NumPy to try out any values between -100 and 100 and see what the answer is.


In [24]:
Candidates = np.linspace(-1000,1000,2001)
#print(Candidates)

for candidate in Candidates:
    if(candidate**2 - 5*candidate +6 ==0):
        print("Just found a possible answer: {}".format(candidate))

Just found a possible answer: 2.0
Just found a possible answer: 3.0


# Adult Dataset 

"Census Income" dataset.

Number of Instances: 48842
Number of Attributes: 14
Date Donated: 1996-05-01
Missing Values?: Yes

### Attributes:

Number of Attributes: 6 continuous, 8 nominal attributes

- age: continuous.
- workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
- fnlwgt: continuous.
- education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
- education-num: continuous.
- marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
- occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
- relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
- race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
- sex: Female, Male.
- capital-gain: continuous.
- capital-loss: continuous.
- hours-per-week: continuous.
- native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
- class: >50K, <=50K



In [25]:
import pandas as pd

adult_df = pd.read_csv('adult.csv')
adult_df.head()

age         workclass  fnlwgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capitalGain  capitalLoss  hoursPerWeek  nativeCountry income  
0         2174            0            40  United-States  <=50K  
1            0            0            13  United-States  <=50K  
2            0            0            40  United-States  <=50K  
3            0            0            40  United-States  <=50K  
4            0            0            40           Cuba  <=50K

In [26]:
type(adult_df.age) 

pandas.core.series.Series

In [27]:
type(adult_df)

pandas.core.frame.DataFrame

In [28]:
adult_df.loc[0].index # Imp

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capitalGain', 'capitalLoss', 'hoursPerWeek', 'nativeCountry',
       'income'],
      dtype='object')

In [29]:
adult_df.age.index #imp

RangeIndex(start=0, stop=32561, step=1)

In [30]:
adult_df.set_index(np.arange(10000,42561),inplace=True)  #imp chnaging index to 10K Series

In [31]:
adult_df.set_index(np.arange(10000,42561))

age         workclass  fnlwgt   education  education-num  \
10000   39         State-gov   77516   Bachelors             13   
10001   50  Self-emp-not-inc   83311   Bachelors             13   
10002   38           Private  215646     HS-grad              9   
10003   53           Private  234721        11th              7   
10004   28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
42556   27           Private  257302  Assoc-acdm             12   
42557   40           Private  154374     HS-grad              9   
42558   58           Private  151910     HS-grad              9   
42559   22           Private  201490     HS-grad              9   
42560   52      Self-emp-inc  287927     HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
10000       Never-married       Adm-clerical  Not-in-family  White    Male   
10001  Married-civ-spouse    Exec-managerial        Husband  White    Male   
10002            Divorced  Handlers-cleaners  Not-in-family  White    Male   
10003  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
10004  Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
42556  Married-civ-spouse       Tech-support           Wife  White  Female   
42557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
42558             Widowed       Adm-clerical      Unmarried  White  Female   
42559       Never-married       Adm-clerical      Own-child  White    Male   
42560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

       capitalGain  capitalLoss  hoursPerWeek  nativeCountry income  
10000         2174            0            40  United-States  <=50K  
10001            0            0            13  United-States  <=50K  
10002            0            0            40  United-States  <=50K  
10003            0            0            40  United-States  <=50K  
10004            0            0            40           Cuba  <=50K  
...            ...          ...           ...            ...    ...  
42556            0            0            38  United-States  <=50K  
42557            0            0            40  United-States   >50K  
42558            0            0            40  United-States  <=50K  
42559            0            0            20  United-States  <=50K  
42560        15024            0            40  United-States   >50K  

[32561 rows x 15 columns]

In [36]:
# adult_df.education-num 

# error expected as hyphen not expected in coulmn

In [35]:
adult_df['education-num'] if hyophen is there then we need to keep this in single quote

10000    13
10001    13
10002     9
10003     7
10004    13
         ..
42556    12
42557     9
42558     9
42559     9
42560     9
Name: education-num, Length: 32561, dtype: int64

In [37]:
adult_df.iloc[2].loc['education']

'HS-grad'

In [38]:
adult_df.education.loc[10002]

'HS-grad'

In [39]:
adult_df['education'].iloc[2]

'HS-grad'

In [40]:
adult_df.at[10002,'education']

'HS-grad'

In [41]:
row_series = adult_df.loc[10002]
print(row_series.loc['education'])
print(row_series.iloc[3])
print(row_series['education'])
print(row_series.education)

HS-grad
HS-grad
HS-grad
HS-grad


In [42]:
columns_series = adult_df.education
print(columns_series.loc[10002])
print(columns_series.iloc[2])
print(columns_series[10002])
# print(row_series.10002)  This will give syntax error!

HS-grad
HS-grad
HS-grad


# Slicing

In [47]:
my_array = np.array([[2,3,5,7],[11,13,17,19],
                     [23,29,31,37,], [41,43,47,49]])
print("my Array is \n\n"  , my_array)

my Array is 

 [[ 2  3  5  7]
 [11 13 17 19]
 [23 29 31 37]
 [41 43 47 49]]


In [48]:
my_array[1,1]

13

In [51]:
my_array[0,0]

2

In [50]:
my_array[0,:]

array([2, 3, 5, 7])

In [49]:
my_array[1,:]

array([11, 13, 17, 19])

In [52]:
my_array[:,1]

array([ 3, 13, 29, 43])

In [53]:
my_array

array([[ 2,  3,  5,  7],
       [11, 13, 17, 19],
       [23, 29, 31, 37],
       [41, 43, 47, 49]])

In [54]:
my_array[1:3,:] # slicing done for n-1 level

array([[11, 13, 17, 19],
       [23, 29, 31, 37]])

In [57]:
my_array[0:4,:] #All 4 rows from 0,1,2,3(Means 3+1 at last)

array([[ 2,  3,  5,  7],
       [11, 13, 17, 19],
       [23, 29, 31, 37],
       [41, 43, 47, 49]])

In [55]:
my_array[1:3,0:2]

array([[11, 13],
       [23, 29]])

In [58]:
my_array[1:3,[0,2]]

array([[11, 17],
       [23, 31]])

In [60]:
adult_df.head()

age         workclass  fnlwgt  education  education-num  \
10000   39         State-gov   77516  Bachelors             13   
10001   50  Self-emp-not-inc   83311  Bachelors             13   
10002   38           Private  215646    HS-grad              9   
10003   53           Private  234721       11th              7   
10004   28           Private  338409  Bachelors             13   

           marital-status         occupation   relationship   race     sex  \
10000       Never-married       Adm-clerical  Not-in-family  White    Male   
10001  Married-civ-spouse    Exec-managerial        Husband  White    Male   
10002            Divorced  Handlers-cleaners  Not-in-family  White    Male   
10003  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
10004  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

       capitalGain  capitalLoss  hoursPerWeek  nativeCountry income  
10000         2174            0            40  United-States  <=50K  
10001            0            0            13  United-States  <=50K  
10002            0            0            40  United-States  <=50K  
10003            0            0            40  United-States  <=50K  
10004            0            0            40           Cuba  <=50K

In [59]:
adult_df.loc[:,'education':'occupation'] #slicing the column

education  education-num      marital-status         occupation
10000   Bachelors             13       Never-married       Adm-clerical
10001   Bachelors             13  Married-civ-spouse    Exec-managerial
10002     HS-grad              9            Divorced  Handlers-cleaners
10003        11th              7  Married-civ-spouse  Handlers-cleaners
10004   Bachelors             13  Married-civ-spouse     Prof-specialty
...           ...            ...                 ...                ...
42556  Assoc-acdm             12  Married-civ-spouse       Tech-support
42557     HS-grad              9  Married-civ-spouse  Machine-op-inspct
42558     HS-grad              9             Widowed       Adm-clerical
42559     HS-grad              9       Never-married       Adm-clerical
42560     HS-grad              9  Married-civ-spouse    Exec-managerial

[32561 rows x 4 columns]

In [62]:
adult_df.sort_values('education-num').reset_index().iloc[1:32561:3617] # Sorting on column
''' we can use .reset_index(), as it has been used in the preceding screenshot. Go ahead and give this 
a try as well. Run adult_df.sort_values('education-num').reset_index(). You will see that the old index is presented as a new column and that the 
new index looks as ordered as any newly read dataset.'''

index  age         workclass  fnlwgt     education  education-num  \
1      23248   68           Private  168794     Preschool              1   
3618   19607   25           Private  251854          11th              7   
7235   38845   31           Private  272856       HS-grad              9   
10852  32759   56           Private  182273       HS-grad              9   
14469  10419   34         State-gov  240283       HS-grad              9   
18086  31532   25      Self-emp-inc   98756  Some-college             10   
21703  17245   37       Federal-gov   40955  Some-college             10   
25320  40595   43           Private  342567     Bachelors             13   
28937  15200   43       Federal-gov  144778     Bachelors             13   
32554  27308   55  Self-emp-not-inc   53566     Doctorate             16   

              marital-status         occupation   relationship   race     sex  \
1              Never-married  Machine-op-inspct  Not-in-family  White    Male   
3618           Never-married       Adm-clerical      Own-child  Black  Female   
7235           Never-married       Craft-repair      Own-child  Black    Male   
10852     Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
14469               Divorced   Transport-moving      Unmarried  White  Female   
18086               Divorced       Adm-clerical      Own-child  White  Female   
21703          Never-married      Other-service      Own-child  White    Male   
25320  Married-spouse-absent       Adm-clerical      Unmarried  White  Female   
28937          Never-married    Exec-managerial  Not-in-family  White    Male   
32554               Divorced    Exec-managerial  Not-in-family  White  Female   

       capitalGain  capitalLoss  hoursPerWeek  nativeCountry income  
1                0            0            10  United-States  <=50K  
3618             0            0            40  United-States  <=50K  
7235             0            0            50        England  <=50K  
10852            0            0            40  United-States  <=50K  
14469            0            0            40  United-States  <=50K  
18086            0            0            50  United-States  <=50K  
21703            0            0            40          Japan  <=50K  
25320            0            0            40  United-States  <=50K  
28937            0            0            40  United-States   >50K  
32554            0            0            30  United-States  <=50K

# Boolean Masking

In [63]:
twopowers_sr = pd.Series([1,2,4,8,16,32,64,128,256,512,1024])
BM = [False,False,False,True,False,False,False,True,True,True,True]
twopowers_sr[BM]

3        8
7      128
8      256
9      512
10    1024
dtype: int64

In [64]:
twopowers_sr >=500

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10     True
dtype: bool

In [65]:
BM = twopowers_sr >=500
twopowers_sr[BM]

9      512
10    1024
dtype: int64

In [66]:
twopowers_sr[twopowers_sr >=500]

9      512
10    1024
dtype: int64

In [ ]:
# calculating the mean and median age of people with preschool education in adult_df.
BM = adult_df.education == 'Preschool'  # Imp
print('Mean: {}'.format(np.mean(adult_df[BM].age)))
print('Median: {}'.format(np.median(adult_df[BM].age)))

In [ ]:
BM1 = adult_df['education-num'] > 10  # Imp
BM2 = adult_df['education-num'] < 10

print('More than 10 years of education - Capital Gain: {}'
      .format(np.mean(adult_df[BM1].capitalGain)))
print('Less than 10 years of education - Capital Gain: {}'
      .format(np.mean(adult_df[BM2].capitalGain)))

# Get to know a dataset

In [ ]:
adult_df.shape

In [ ]:
adult_df.columns

In [ ]:
adult_df.columns = ['age', 'workclass', 'fnlwgt', 'education', 
                    'education_num', 'marital_status', 'occupation',
                    'relationship', 'race', 'sex', 'capitalGain',
                    'capitalLoss', 'hoursPerWeek', 'nativeCountry',
                    'income']

In [ ]:
adult_df.describe()

In [ ]:
adult_df.age.plot.hist()

In [ ]:
adult_df.relationship.unique()

In [ ]:
adult_df.relationship.value_counts()

In [ ]:
adult_df.relationship.value_counts().plot.bar()

# Appy a function

In [ ]:
def MultiplyBy2(n):
    return n*2

adult_df.age.apply(MultiplyBy2)

### Applying a Function - Analytic Example 1
Divide every value in column fnlwgt by the sum of all its values.

In [ ]:
total_fnlwgt = adult_df.fnlwgt.sum()

def CalculatePercentage(v):
    return v/total_fnlwgt*100

adult_df.fnlwgt = adult_df.fnlwgt.apply(CalculatePercentage)
adult_df

In [ ]:
total_fnlwgt = adult_df.fnlwgt.sum()

adult_df.fnlwgt = adult_df.fnlwgt.apply(lambda v: v/total_fnlwgt*100)
adult_df

In [ ]:
def CalcLifeNoEd(row):
    return row.age - row.education_num

adult_df.apply(CalcLifeNoEd,axis=1)

In [ ]:
adult_df.apply(lambda r: r.age-r.education_num,axis=1)

In [ ]:
adult_df['lifeNoEd'] = adult_df.apply(
    lambda r: r.age-r.education_num,axis=1)

adult_df['capitalNet'] = adult_df.apply(
    lambda r: r.capitalGain - r.capitalLoss,axis=1)

adult_df[['education_num','lifeNoEd','capitalNet']].corr()

# Groupby

In [ ]:
adult_df.groupby(['marital_status','sex']).age.median()

In [ ]:
adult_df.groupby(['race','sex']).capitalNet.mean()

In [ ]:
grb_result =adult_df.groupby(['race','sex']).capitalNet.mean()

print(grb_result.index)

In [ ]:
grb_result =adult_df.groupby(['race','sex']).capitalNet.mean()
grb_result

In [ ]:
grb_result.unstack()

In [ ]:
mlt_seris =adult_df.groupby(['race','sex','income']).fnlwgt.mean()
mlt_seris

In [ ]:
mlt_seris.unstack()

In [ ]:
mlt_seris.unstack().unstack()

In [ ]:
mlt_df= mlt_seris.unstack().unstack()
mlt_df.columns

In [ ]:
mlt_df.stack()

In [ ]:
mlt_df.stack().stack()

# Pivot & Melt

In [ ]:
wide_df = pd.read_csv('wide.csv')
wide_df

In [ ]:
wide_df.melt(id_vars='ReadingDateTime',
             value_vars=['NO','NO2','NOX','PM10','PM2.5'],
             var_name='Species',
             value_name='Value')

In [ ]:
long_df = pd.read_csv('long.csv')
long_df

In [ ]:
long_df.pivot(index='ReadingDateTime',
              columns='Species',
              values='Value')